#!/bin/bash

# delete node_modules and packages
npm run clean

# install first pass of node_modules (@nil-/mono-{})
npm install

# generate packages
npm run build -ws

# rename package.json's name for generated packages
# node scripts/postbuild

# reinstall to generate links to generated packages
# npm install
